### ISSUE TITLE
Access Denied

### ISSUE THREAD

**Issue by jtara1** [AceLewis/SteamHolidaySale2015CardAutoHarvester#2]
This might be the same issue as #1. I let the script run, wasn't watching it, and came back to find this.

![image](https://user-images.githubusercontent.com/7478231/34323333-b161fa04-e7f9-11e7-939b-fd73d77b263b.png)

edit: It seems I've been banned from the store page (in client and in browser). Hopefully it's just a temp ban or IP ban. It better not be tied to my acc permanently.

edit2: A few hours later I'm not longer getting `Access Denied` when visiting the steam store, but the problem of the script completing one discovery queue cycle then getting Access Denied still exists.

**Comment by AceLewis** [comment]
I can't recreate this issue, I don't get access denied. What else do you have in your setup? Browser, extensions ect.

**Comment by jtara1** [comment]
I disabled Enhanced Steam (might be irrelevant) and watched it run this time. It completed 5 queues and earned 2 cards before I stopped it. Steam didn't want to give me a 3rd card for this today, and the script didn't seem to meet it's terminate requirements. Using chrome 63.0.3239.84 

edit: I got two cards for voting, steam servers might be lagging?

**Comment by jtara1** [comment]
I ran it again, and it works. There was no terminating condition so I'm guessing the user is expected to watch it and stop it in some way.

Access Denied error may have come from some type of anti-ddos system of steam's, idk.
